services:
- docker

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build --no-cache -t $DOCKER_USERNAME/openvas-docker-lite:9 .
- docker push $DOCKER_USERNAME/openvas-docker-lite
